#ifndef _ERROR_INFO_H_
#define _ERROR_INFO_H_

const int kPARSING_ERROR_NO_ERROR = 0;

const int kPARSING_SPS_ERROR_SCALING_MATRIX = -1;
const int kPARSING_SPS_ERROR_UNSUPPORTED_POC_TYPE = -2;
const int kPARSING_PPS_ERROR_UNSUPPORTED_NUM_SLICE_GROUP = -3;

const int kPARSING_CAVLC_CODE_NOT_FOUND = -25;

const int kPARSING_INVALID_PRED_MODE = -100;


#endif
